# Generated by Django 4.1.5 on 2023-01-12 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="rss_cache",
        ),
    ]
