# Generated by Django 4.1.4 on 2023-01-06 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="full_name",
            new_name="username",
        ),
    ]
