# Generated by Django 4.1.4 on 2023-01-06 17:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "author_name",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("block", models.CharField(blank=True, max_length=128, null=True)),
                ("text", models.TextField()),
                ("html_cache", models.TextField(null=True)),
                ("metadata", models.JSONField(null=True)),
                ("ipaddress", models.GenericIPAddressField(null=True)),
                ("useragent", models.CharField(max_length=512, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("upvotes", models.IntegerField(db_index=True, default=0)),
                ("is_visible", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_pinned", models.BooleanField(default=False)),
                ("deleted_by", models.UUIDField(null=True)),
            ],
            options={
                "db_table": "comments",
                "ordering": ["created_at"],
            },
        ),
    ]
