# Generated by Django 4.1.5 on 2023-01-12 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0004_remove_comment_deleted_by_remove_comment_is_visible"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ("created_at",)},
        ),
    ]
