# Generated by Django 4.1.4 on 2023-01-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Subscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=256, unique=True)),
                ("secret_hash", models.CharField(max_length=256, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("bounces", models.IntegerField(default=0)),
                ("data", models.JSONField(blank=True, null=True)),
                ("is_confirmed", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "subscribers",
                "ordering": ("-created_at",),
            },
        ),
    ]
