# Generated by Django 5.1.5 on 2025-02-18 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inside', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='lang',
            field=models.CharField(default='ru', max_length=2),
        ),
    ]
