# Generated by Django 4.1.5 on 2023-01-12 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0003_alter_comment_options_alter_comment_created_at_and_more"),
        ("clickers", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clicker",
            name="block",
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name="clicker",
            name="comment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clickers",
                to="comments.comment",
            ),
        ),
    ]
